import { NextPage } from "next";
import Head from "next/head";
import Content from "@/components/content";
import Footer from "@/components/footer";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>All Link HMSE</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <main className="w-screen flex flex-col justify-center items-center my-12">
        <div className="bg-white bg-opacity-20 container max-w-screen-lg py-4 rounded-2xl w-fit md:w-full px-4 md:px-0">
          <Content />
        </div>
        <Footer/>
      </main>
    </>
  );
};

export default Index;
